# Generated by Django 4.1.3 on 2022-11-08 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("chennai", "chennai"),
                            ("bangalore", "bangalore"),
                            ("mumbai", "mumbai"),
                            ("cochin", "cochin"),
                            ("dehli", "dehli"),
                            ("panjab", "panjab"),
                            ("gujarat", "gujarat"),
                            ("calicut", "calicut"),
                        ],
                        default="bangalore",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.TextField()),
                ("photo", models.ImageField(blank=True, upload_to="user-profile/")),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(auto_now_add=True)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "designation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.designation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
