# Generated by Django 4.1.3 on 2022-11-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="users",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterField(
            model_name="designation",
            name="designation",
            field=models.CharField(
                choices=[
                    ("QA Lead", "QA Lead"),
                    ("Engineer", "Engineer"),
                    ("Developer", "Developer"),
                    ("Admin", "Admin"),
                    ("QA tester", "QA tester"),
                ],
                default="bangalore",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
